version: '3.1'
services:
 postgres:
   image: postgres:12-alpine
   ports:
     - '5432:5432'
   volumes:
       - ./data:/var/lib/postgres
   environment:
       - POSTGRES_DB=db
       - POSTGRES_USER=petya
       - POSTGRES_PASSWORD=qwerty123